### ISSUE TITLE
Gradle sync failed: Null extracted folder for artifact: 

### ISSUE THREAD

**Issue by QGB** [iamr0s/XposedMiShare#1]
Gradle sync failed: Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=androidx.fragment:fragment:1.3.6, variant=androidx.fragment:fragment:1.3.6, variantName=null, artifactFile=C:\Users\qgb\.gradle\caches\modules-2\files-2.1\androidx.fragment\fragment\1.3.6\6391fc504e7c0f24051ac8b9da3f0ba4d1241dff\fragment-1.3.6.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=C:\test\github\luckyzyxtools}) (3 m 53 s 199 ms)

![image](https://user-images.githubusercontent.com/8005654/170967631-8d032cf1-35e2-4518-94b5-a86429a90e96.png)

**Comment by iamr0s** [comment]
你这个Issue和这个项目好像没什么关系吧。
这个是你网络有问题，Gradle刷新失败了，具体再自己排查一下吧。
Your issue seems to have nothing to do with this project.
This is because there is a problem with your network. Gradle failed to sync. Check it by yourself.

**Comment by QGB** [comment]
studio reopen project, build success

但是安装apk 时 显示 解析软件包时出现问题

**Comment by QGB** [comment]
8.1 系统

**Comment by iamr0s** [comment]
clear build,then Rebuild it
